"""Tests for the daily account-status push in ``status_report()``.

The push is generated by the bot itself, on the same schedule slot and
trading-day guard as the rest of ``status_report()`` — no separate job, no
external script. A formatting bug or a flaky Alpaca call in this feature must
never be able to break the rest of the job (see ``_check_for_mass_exit`` for
the same pattern applied to ``post_close_scan``).
"""

from datetime import datetime, timezone

import pytest

import meansrev_main as main


def _position(symbol, qty=10, entry=100.0, current=105.0, pl=50.0, plpc=0.05):
    class _Pos:
        pass

    p = _Pos()
    p.qty = qty
    p.avg_entry_price = entry
    p.current_price = current
    p.unrealized_pl = pl
    p.unrealized_plpc = plpc
    return {symbol: p}


@pytest.fixture
def harness(monkeypatch):
    """Wire status_report to stubs and capture what it tries to push."""
    pushed = []

    monkeypatch.setattr(main.executor, "is_trading_day_today", lambda: True)
    monkeypatch.setattr(main, "eval_checkpoint",
                        type("_cp", (), {"check_and_notify": staticmethod(
                            lambda: {"new": 0, "target": 25, "reached": False})}))
    monkeypatch.setattr(main.pt, "all_positions", lambda: {})

    snapshot = {
        "equity": 10500.0,
        "last_equity": 10400.0,
        "base_value": 10000.0,
        "base_value_asof": "2026-01-02",
    }
    monkeypatch.setattr(main.executor, "get_account_snapshot", lambda: snapshot)
    monkeypatch.setattr(main.executor, "get_alpaca_positions", lambda: {})
    monkeypatch.setattr(main.notifier, "send_daily_status",
                        lambda snap, pos, sweep=None: pushed.append((snap, pos)))

    return {"pushed": pushed, "snapshot": snapshot}


def test_a_non_trading_day_makes_no_alpaca_calls_and_sends_no_push(monkeypatch, harness):
    monkeypatch.setattr(main.executor, "is_trading_day_today", lambda: False)
    calls = []
    monkeypatch.setattr(main.executor, "get_account_snapshot", lambda: calls.append(1))
    monkeypatch.setattr(main.executor, "get_alpaca_positions", lambda: calls.append(1))

    main.status_report()

    assert calls == [], "Alpaca was called on a day the market is closed"
    assert harness["pushed"] == []


def test_zero_open_positions_still_sends_the_push(harness):
    """Flat is a normal day, not an error path — the push must still go out."""
    main.status_report()

    assert len(harness["pushed"]) == 1
    snap, positions = harness["pushed"][0]
    assert snap == harness["snapshot"]
    assert positions == {}


def test_a_failed_snapshot_does_not_propagate(monkeypatch, harness):
    def _boom():
        raise RuntimeError("alpaca said no")

    monkeypatch.setattr(main.executor, "get_account_snapshot", _boom)

    main.status_report()  # must not raise

    assert harness["pushed"] == []


def test_a_failed_push_does_not_propagate(monkeypatch, harness):
    def _boom(snap, pos, sweep=None):
        raise RuntimeError("ntfy is down")

    monkeypatch.setattr(main.notifier, "send_daily_status", _boom)

    main.status_report()  # must not raise


def test_the_title_is_paper_prefixed_in_paper_mode(monkeypatch):
    """A paper push must never be mistaken for a live account's numbers."""
    import config
    import notifier

    monkeypatch.setattr(config, "PAPER", True)
    monkeypatch.setattr(config, "NTFY_TOPIC", "test-topic")

    sent = []
    monkeypatch.setattr(notifier.requests, "post",
                        lambda url, json, timeout: sent.append(json))

    notifier.send_daily_status(
        {"equity": 100.0, "last_equity": 100.0, "base_value": 100.0,
         "base_value_asof": "2026-01-02"},
        {},
    )

    assert len(sent) == 1
    assert sent[0]["title"].startswith("[PAPER]")
